version: '3.8'
services:
  postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - /data:/var/lib/postgresql/data
    container_name: postgresql
    ports:
      - $DB_DOCKER_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_DOCKER_PORT
    networks:
      - my-network

  challenge:
    container_name: challenge
    depends_on:
      - postgres
    links:
      - postgres
    build: .
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/$DB_DATABASE?sslmode=disable&connect_timeout=5",
        "spring.datasource.username" : "challenge",
        "spring.datasource.password" : "challenge",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
