spring:
  application:
    name: challenge
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: challenge
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://34.172.228.204/postgres?sslmode=disable&connect_timeout=5
  cloud:
    gcp:
      sql:
        database-name: postgres
        instance-connection-name: sublime-index-437717-v1:us-central1:challenge
  sql:
    init:
      mode: always

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
jwt:
  secret:
    key: 5A7B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B1C2D3E4F5A6B7C8D9E0F1
hibernate:
  globally_quoted_identifiers: 'true'
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: ''
config:
  api:
    base-path: /api/

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /api
    enabled: true