spring:
  application:
    name: challenge
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///postgres
    username: postgres
    password: challenge
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance:
        enableIamAuth: true
        sslmode: disable

  sql:
    init:
      mode: always

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
jwt:
  secret:
    key: 5A7B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B1C2D3E4F5A6B7C8D9E0F1
hibernate:
  globally_quoted_identifiers: 'true'
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: ''
config:
  api:
    base-path: /api/

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /api
    enabled: true